### ISSUE TITLE
General error during semantic analysis: Unsupported class file major version 61

### ISSUE THREAD

**Issue by prashanthi-r** [titipata/scipdf_parser#16]
When I run `bash serve_grobid.sh`, I encounter the following error

I'm using GROBID version 0.6.2, Java version 17.0.4 and Gradle version 8.1

```> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(As ....```

**Comment by Irazall** [comment]
same here, found two pointers here:
https://stackoverflow.com/questions/73340168/general-error-during-conversion-unsupported-class-file-major-version-62-ionic-e
https://stackoverflow.com/questions/67079327/how-can-i-fix-unsupported-class-file-major-version-60-in-intellij-idea

**Comment by lfoppiano** [comment]
@prashanthi-r version 0.6.2 was not compatible with JDK 17. You have to update to at least 0.7.3. 
To avoid such issues, you might want to try to use docker instead? 

I opened a PR https://github.com/titipata/scipdf_parser/pull/20 for doing so
