### ISSUE TITLE
Pillow should be required at the install

### ISSUE THREAD

**Issue by GLambard** [titipata/scipdf_parser#27]
**Issue**: 

```
>>> import scipdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guillaume/miniconda3/envs/grobid_python/lib/python3.9/site-packages/scipdf/__init__.py", line 6, in <module>
    from scipdf.pdf.parse_pdf import *
  File "/home/guillaume/miniconda3/envs/grobid_python/lib/python3.9/site-packages/scipdf/pdf/__init__.py", line 1, in <module>
    from .parse_pdf import *
  File "/home/guillaume/miniconda3/envs/grobid_python/lib/python3.9/site-packages/scipdf/pdf/parse_pdf.py", line 10, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Solution**:

`pip install Pillow`

Cheers!

**Comment by prateek-dagar** [comment]
Raise PR#33 for fix of this issue.

https://github.com/titipata/scipdf_parser/pull/33
